/**
 * /about-me — "Meet the Engineer" page.
 *
 * Personal introduction page complementing the project work shown on
 * /projects. The portfolio so far has been "what I've shipped" — this
 * page is "who I am". Hiring panels typically read both before deciding
 * whether to interview, so we want the same polish here that's elsewhere.
 *
 * Section order (the section ids match `AboutSectionNav`):
 *   1. Hero            — pfp + name + role + tight pitch + CTA chips + facts
 *   2. #story          — vertical career timeline + education + languages
 *   3. #values         — 4 values, each anchored to a real project/moment
 *   4. #now            — Sivers-style "what I'm working on this month"
 *   5. #resume         — native dark-themed render of the one-page resume
 *   6. #cv             — native dark-themed render of the multi-page CV
 *   7. #contact        — closing CTA
 *
 * Server Component. Reveal animations and the sticky scroll-spy nav are
 * client islands.
 *
 * `metadata.title` is overridden so the tab + share-card read "Meet the
 * Engineer — Shamar T. Patnett" via the root layout's title template.
 */

import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import {
  Briefcase,
  Code,
  Download,
  ExternalLink,
  MapPin,
  Mail,
  Phone,
  TrendingUp,
} from "lucide-react";

import { Section } from "@/components/ui/Section";
import { Reveal } from "@/components/animations/Reveal";
import { SITE, SOCIALS } from "@/lib/constants";

// /about-me-specific feature components — owned by this page.
import { AboutSectionNav } from "@/components/about/AboutSectionNav";
import { CareerTimeline } from "@/components/about/CareerTimeline";
import { CvNative } from "@/components/about/CvNative";
import { EducationBlock } from "@/components/about/EducationBlock";
import { InterestsStrip } from "@/components/about/InterestsStrip";
import { LanguagesStrip } from "@/components/about/LanguagesStrip";
import { NowBlock } from "@/components/about/NowBlock";
import { PrintButton } from "@/components/about/PrintButton";
import { ResumeNative } from "@/components/about/ResumeNative";

export const metadata: Metadata = {
  title: "Meet the Engineer",
  description:
    "Shamar T. Patnett — IT Manager and software engineer, founder of M3M3 Development. Belmopan, Belize. Open to roles on either track. Resume + CV preview and download.",
};

// ─── Quick-facts grid ─────────────────────────────────────────────────────
//
// Replaces "Role" + "Education" cells with impact-metric cells. Education
// now lives in its own dedicated `<EducationBlock />` further down, where
// it can show modules + certificate ID without crowding this strip.
const QUICK_FACTS = [
  {
    label: "Open to",
    value: "IT Manager · Software Engineer",
    Icon: Briefcase,
  },
  {
    label: "In production",
    value: "287K LOC · M3 Marketplace · live on GCP",
    Icon: TrendingUp,
  },
  {
    label: "Track record",
    value: "5+ yrs IT · 4+ yrs leading dev team",
    Icon: Code,
  },
  {
    label: "Location",
    value: "Belmopan, Belize",
    Icon: MapPin,
  },
] as const;

// Document sources. The HTML files live in /public/about/ alongside the
// profile picture; the PDFs are generated by the user via browser print
// from the same HTML and dropped at the same paths. If a PDF doesn't
// exist yet, the link 404s gracefully — and a Print button is offered
// as an immediate fallback.
const DOCS = {
  resumeHtml: "/about/resume.html",
  resumePdf: "/about/resume.pdf",
  cvHtml: "/about/cv.html",
  cvPdf: "/about/cv.pdf",
  demoHtml: "/about/demo-readme.html",
  demoPdf: "/about/demo-readme.pdf",
} as const;

// ─── Values strip data ────────────────────────────────────────────────────
//
// Each value now anchors to a specific project/moment via `tag`. Body
// copy refers to the actual moment when honest to do so.
//
// `as const` + `ReadonlyArray` => array literal types are preserved and
// nothing here can be mutated by accident.
type Value = Readonly<{ title: string; tag: string; body: string }>;

const VALUES: ReadonlyArray<Value> = [
  {
    title: "Ownership",
    tag: "BSIF · 2024–present",
    body: "Sole IT authority means procurement, infrastructure, security, vendor SLAs, and the staff who walk in with broken laptops. Not aspirations — this is the daily job at BSIF.",
  },
  {
    title: "Ship, then iterate",
    tag: "M3 Marketplace · 2023",
    body: "287K LOC of M3 Marketplace got there one production deploy at a time. Small, secure things shipped this sprint beat a perfect thing for next quarter that never lands.",
  },
  {
    title: "Security as a default",
    tag: "TraySoft · 2024",
    body: "MFA, biometric login, PCI-DSS tokenization, audit logging — baseline, not selling points. The TraySoft payment module ships them on by default for any project that picks it up.",
  },
  {
    title: "Continuous learning",
    tag: "Self-taught · ongoing",
    body: "Picked up Flutter, Serverpod, pgvector, Cloud Run, Qt/QML, and Tailwind v4 the same way: a real project, a deadline, and the documentation. Angular and Groovy land the same way next.",
  },
] as const;

export default function AboutMePage(): React.JSX.Element {
  return (
    <>
      {/* ── HERO ─────────────────────────────────────────────────────────── */}
      <Section eyebrow="Meet the engineer" title={SITE.author}>
        <Reveal direction="up" amount={0.2}>
          <div className="grid grid-cols-1 gap-8 md:grid-cols-5">
            {/* Avatar — uses next/image for optimization. Wrapped in a glass
                ring so it sits visually consistent with the rest of the
                site's card style. `priority` because this is above the fold. */}
            <div className="md:col-span-2">
              <div className="relative mx-auto aspect-square w-56 overflow-hidden rounded-3xl ring-1 ring-white/10 sm:w-72 md:mx-0 md:w-full md:max-w-sm">
                <Image
                  src="/about/pfp.jpeg"
                  alt={`${SITE.author} — profile photo`}
                  fill
                  priority
                  sizes="(min-width: 768px) 28rem, 18rem"
                  className="object-cover"
                />
                {/* Soft inner gradient for depth */}
                <div
                  aria-hidden
                  className="pointer-events-none absolute inset-0 bg-gradient-to-tr from-accent-cyan/10 via-transparent to-accent-violet/15"
                />
              </div>
            </div>

            {/* Name block + tightened pitch + CTA chips.

                The pitch is intentionally short — punch line, then two
                proof sentences, total <50 words. Old version was ~85
                words across 4 sentences which buried the lede. */}
            <div className="md:col-span-3">
              <span className="font-mono text-xs uppercase tracking-[0.2em] text-accent-cyan">
                {SITE.role}
              </span>
              <p className="mt-4 text-pretty text-base leading-relaxed text-foreground-muted sm:text-lg">
                <span className="font-semibold text-foreground">
                  IT Manager and software engineer in Belmopan.
                </span>{" "}
                Sole IT authority at the Belize Social Investment Fund;
                founder of M3M3 Development, where I led a team to ship a
                live 287K-LOC marketplace with Belize Bank payments in
                production. Open to roles on either track.
              </p>

              {/* Direct contact + downloads — chip-row mirrors the project
                  links style on /projects so the page feels of-a-piece. */}
              <div className="mt-6 flex flex-wrap gap-2">
                <a
                  href={`mailto:${SITE.email}`}
                  className="inline-flex items-center gap-2 rounded-full bg-accent-cyan/20 px-4 py-2 text-xs font-medium text-accent-cyan ring-1 ring-accent-cyan/40 transition hover:bg-accent-cyan/30"
                >
                  <Mail className="h-3.5 w-3.5" aria-hidden />
                  {SITE.email}
                </a>
                <a
                  href={`tel:${SITE.phone.replace(/[^+\d]/g, "")}`}
                  className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-4 py-2 text-xs font-medium text-foreground transition hover:border-white/20"
                >
                  <Phone className="h-3.5 w-3.5" aria-hidden />
                  {SITE.phone}
                </a>
                <a
                  href={SOCIALS.github}
                  target="_blank"
                  rel="noreferrer"
                  className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-4 py-2 text-xs font-medium text-foreground transition hover:border-white/20"
                >
                  <ExternalLink className="h-3.5 w-3.5" aria-hidden />
                  GitHub
                </a>
                <a
                  href={SOCIALS.linkedin}
                  target="_blank"
                  rel="noreferrer"
                  className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-4 py-2 text-xs font-medium text-foreground transition hover:border-white/20"
                >
                  <ExternalLink className="h-3.5 w-3.5" aria-hidden />
                  LinkedIn
                </a>
              </div>

              {/* Quick-facts strip. Education was pulled out into its own
                  block (see #story below) so this row can carry impact
                  metrics that better serve hiring-panel scanning. */}
              <dl className="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-4">
                {QUICK_FACTS.map((fact) => {
                  const Icon = fact.Icon;
                  return (
                    <div
                      key={fact.label}
                      className="rounded-xl border border-white/10 bg-white/[0.03] p-3"
                    >
                      <div className="flex items-center gap-2 font-mono text-[10px] uppercase tracking-wider text-foreground-muted">
                        <Icon className="h-3 w-3" aria-hidden />
                        {fact.label}
                      </div>
                      <div className="mt-1.5 text-sm font-semibold text-foreground">
                        {fact.value}
                      </div>
                    </div>
                  );
                })}
              </dl>
            </div>
          </div>
        </Reveal>
      </Section>

      {/* ── STICKY SECTION NAV ─────────────────────────────────────────────
          Sits below the hero and above the rest of the page. Sticky scroll-
          spy implemented as a client island; everything else stays SSR. */}
      <AboutSectionNav />

      {/* ── #story — Career timeline + Education + Languages ───────────── */}
      <Section
        id="story"
        eyebrow="Story"
        title="How I got here."
        description="Five inflection points that shaped the IT Manager + software engineer skill set."
      >
        {/*
          Two-column layout on lg+: the timeline on the left, education +
          languages stacked on the right. Stacks vertically on small screens.
        */}
        <div className="grid grid-cols-1 gap-8 lg:grid-cols-[1.4fr_1fr]">
          <div>
            <CareerTimeline />
          </div>

          <div className="space-y-4">
            <EducationBlock />
            <LanguagesStrip />
            <InterestsStrip />
          </div>
        </div>
      </Section>

      {/* ── #values — Anchored values ──────────────────────────────────── */}
      <Section
        id="values"
        eyebrow="What I value"
        title="How I work, and why."
        description="Each one tagged to the project where it shows up in practice."
      >
        <Reveal direction="up" amount={0.15}>
          <div className="grid grid-cols-1 gap-3 md:grid-cols-2">
            {VALUES.map((v) => (
              <div
                key={v.title}
                className="glass relative rounded-2xl p-5 transition hover:bg-white/10"
              >
                {/* Project/moment tag in the corner — small chip */}
                <div className="absolute right-4 top-4 rounded-full border border-white/10 bg-white/[0.04] px-2 py-0.5 font-mono text-[9px] uppercase tracking-wider text-foreground-muted">
                  {v.tag}
                </div>

                <div className="font-mono text-[10px] uppercase tracking-[0.2em] text-accent-cyan">
                  {v.title}
                </div>
                <p className="mt-2 text-sm leading-relaxed text-foreground-muted">
                  {v.body}
                </p>
              </div>
            ))}
          </div>
        </Reveal>
      </Section>

      {/* ── #now — Sivers-style /now block ─────────────────────────────── */}
      <Section id="now" className="pt-0">
        <NowBlock />
      </Section>

      {/* ── #resume — Native render ────────────────────────────────────── */}
      <DocSection
        id="resume"
        eyebrow="Resume"
        title="One-page resume."
        description="Designed for hiring panels — the IT Manager and software engineering pitch on a single page. Rendered natively in the site theme; the printable version is one click away."
        htmlSrc={DOCS.resumeHtml}
        pdfSrc={DOCS.resumePdf}
        downloadName="Shamar_Patnett_IT_Manager_Resume"
      >
        <ResumeNative />
      </DocSection>

      {/* ── #cv — Native render ────────────────────────────────────────── */}
      <DocSection
        id="cv"
        eyebrow="Curriculum Vitae"
        title="Full CV."
        description="Extended CV with full project detail, technical skills matrix, and professional competencies. The cover letter for specific applications lives in the original HTML."
        htmlSrc={DOCS.cvHtml}
        pdfSrc={DOCS.cvPdf}
        downloadName="Shamar_Patnett_IT_Manager_CV"
      >
        <CvNative />
      </DocSection>

      {/* ── #demo — Boledo v2 demo APK readme ──────────────────────────── */}
      {/*
        This is a special section: I built a working Android demo of a next
        version of BGLL's Fi We Boledo app in 13 days as part of the IT
        Manager application. The readme HTML walks reviewers through what's
        different, how to install, and a 5-minute tour. Rendered as an
        iframe of the original styled HTML so the printable side-by-side
        comparison stays intact (no need for a separate native renderer).
      */}
      <DocSection
        id="demo"
        eyebrow="Boledo v2 Demo · BGLL"
        title="13-day working Android demo."
        description="A real, installable Android APK I built between April 27 and May 10, 2026 — submitted with my IT Manager application. Bank-card payments, biometric login, masked PII, redesigned game flows. Open the readme for install steps + a side-by-side comparison."
        htmlSrc={DOCS.demoHtml}
        pdfSrc={DOCS.demoPdf}
        downloadName="Boledo_v2_Demo_Readme"
      >
        {/*
          No native render for the demo readme — the original HTML is
          already self-contained with side-by-side comparison cards and
          install steps. Embed it directly. Sandbox restricts what the
          embedded page can do (no top-level navigation), `loading="lazy"`
          defers the fetch until the user scrolls here.
        */}
        <div className="glass overflow-hidden rounded-2xl">
          <iframe
            src={DOCS.demoHtml}
            title="Boledo v2 Demo readme"
            className="block h-[80vh] w-full border-0 bg-white"
            sandbox="allow-same-origin allow-popups"
            loading="lazy"
          />
        </div>
      </DocSection>

      {/* ── #contact — Closing CTA ─────────────────────────────────────── */}
      <Section id="contact" className="pb-28">
        <Reveal>
          <div className="glass relative overflow-hidden rounded-3xl p-8 sm:p-12">
            <div className="flex flex-col items-start gap-6 sm:flex-row sm:items-center sm:justify-between">
              <div className="max-w-2xl">
                <span className="font-mono text-xs uppercase tracking-[0.2em] text-accent-cyan">
                  Want to talk
                </span>
                <h3 className="mt-3 text-balance text-2xl font-semibold tracking-tight sm:text-3xl">
                  Open to IT Manager &amp; Software Engineering roles in Belize.
                </h3>
                <p className="mt-3 text-foreground-muted">
                  Direct line below — happy to walk through the Belize Bank
                  integration, the M3 Marketplace architecture, or the
                  Angular/Groovy ramp plan in detail.
                </p>
              </div>
              <Link
                href="/contact"
                className="inline-flex items-center gap-2 rounded-xl bg-foreground px-5 py-3 text-sm font-medium text-background transition hover:opacity-90"
              >
                Contact me
              </Link>
            </div>
          </div>
        </Reveal>
      </Section>
    </>
  );
}

// ─── DocSection: shared layout for the Resume and CV previews ─────────────
//
// Each preview shows: header, action chips (PDF + open original + print),
// and the native render passed in as `children`. The native render is
// where the heavy lifting happens — this component just wraps with the
// page chrome.
//
// Concept showcase:
//  - **Slot pattern** via `children`: instead of forking this into two
//    separate components for resume vs CV, we accept the body via
//    `children` and let callers decide what to render. Shorter + reusable.
//  - PDF link uses the `download` attribute. If the file is missing (no
//    PDF generated yet), the link 404s — but we mitigate UX risk by
//    exposing a "Print this section" client button, which always works.
function DocSection({
  id,
  eyebrow,
  title,
  description,
  htmlSrc,
  pdfSrc,
  downloadName,
  children,
}: {
  id?: string;
  eyebrow: string;
  title: string;
  description: string;
  htmlSrc: string;
  pdfSrc: string;
  downloadName: string;
  children: React.ReactNode;
}) {
  return (
    <Section id={id} eyebrow={eyebrow} title={title} description={description}>
      <Reveal direction="up" amount={0.15}>
        {/* Action row: PDF download + open original HTML + print fallback. */}
        <div className="mb-4 flex flex-wrap items-center gap-2">
          <a
            href={pdfSrc}
            // The `download` attribute hints the browser to save instead of
            // navigate. Falls back gracefully if the PDF isn't there yet.
            download={`${downloadName}.pdf`}
            className="inline-flex items-center gap-2 rounded-full bg-foreground px-4 py-2 text-xs font-medium text-background transition hover:opacity-90"
          >
            <Download className="h-3.5 w-3.5" aria-hidden />
            Download PDF
          </a>
          <a
            href={htmlSrc}
            target="_blank"
            rel="noreferrer"
            className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-4 py-2 text-xs font-medium text-foreground transition hover:border-white/20"
          >
            <ExternalLink className="h-3.5 w-3.5" aria-hidden />
            Open original HTML
          </a>
          <PrintButton />
          {/* Helper note explaining that the PDF may not exist yet. Subtle. */}
          <span className="text-[11px] italic text-foreground-muted">
            (PDF coming — print this page in the meantime.)
          </span>
        </div>

        {/* The body — native rendered resume/CV passed by the caller. */}
        {children}
      </Reveal>
    </Section>
  );
}
